In [22]:
import pandas as pd
import numpy as np
from sklearn.decomposition import pca
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn import metrics
norm_data = pd.read_csv("../csv/expanded_dataset_norm_v1.csv")
data = norm_data.drop(['Class'], axis=1)
target = norm_data['Class']

In [23]:
# svm normalized data
from sklearn import svm
rbf_svc = svm.SVC(kernel='rbf', C = 2 ** 13, gamma=(2 ** -12))
predicted = cross_val_predict(rbf_svc, data, target, cv=10, n_jobs=-1)
print metrics.accuracy_score(target, predicted)
metrics.confusion_matrix(target, predicted, labels=["normal", "flooding", "slowloris"])

0.845401174168


array([[461,  76,  29],
       [ 44, 215,   0],
       [  9,   0, 188]])

In [24]:
#ANN normalized data
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(solver='lbfgs', max_iter=1000, activation='logistic', alpha=1e-5, hidden_layer_sizes=(5), random_state=7)
predicted = cross_val_predict(mlp, data, target, cv=10)
print metrics.accuracy_score(target, predicted)
metrics.confusion_matrix(target, predicted, labels=["normal", "flooding", "slowloris"])

0.791585127202


array([[496,  70,   0],
       [118, 141,   0],
       [ 20,   5, 172]])

In [25]:
#random forest normalized data
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=10)
predicted = cross_val_predict(rfc, data, target, cv=10)
print metrics.accuracy_score(target, predicted)
metrics.confusion_matrix(target, predicted, labels=["normal", "flooding", "slowloris"])

0.839530332681


array([[448,  89,  29],
       [ 44, 215,   0],
       [  2,   0, 195]])

In [26]:
pcaa = pca.PCA(5, copy=True, whiten=True)
pca_data = pcaa.fit(data).transform(data)

In [27]:
#svm pca data
from sklearn import svm
rbf_svc = svm.SVC(kernel='rbf', C = 2 ** 9, gamma=2 ** -4)
predicted = cross_val_predict(rbf_svc, pca_data, target, cv=10)
print metrics.accuracy_score(target, predicted)
metrics.confusion_matrix(target, predicted, labels=["normal", "flooding", "slowloris"])


0.83072407045


array([[470,  87,   9],
       [ 74, 185,   0],
       [  3,   0, 194]])

In [28]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(solver='lbfgs', max_iter=1000, activation='logistic', alpha=1e-5, hidden_layer_sizes=(3,))
predicted = cross_val_predict(mlp, pca_data, target, cv=10)
metrics.accuracy_score(target, predicted)
print metrics.accuracy_score(target, predicted)
metrics.confusion_matrix(target, predicted, labels=["normal", "flooding", "slowloris"])

0.795499021526


array([[456, 107,   3],
       [ 98, 161,   0],
       [  1,   0, 196]])

In [29]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=10)
predicted = cross_val_predict(rfc, pca_data, target, cv=10)
print metrics.accuracy_score(target, predicted)
metrics.confusion_matrix(target, predicted, labels=["normal", "flooding", "slowloris"])

0.785714285714


array([[413, 125,  28],
       [ 56, 203,   0],
       [ 10,   0, 187]])